name: Js-sdsl Benchmark CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Install dependencies
      run: yarn install
    - name: Generate README
      run: yarn generate && mv README.md docs/resultAnalyze.md && mv README.zh-CN.md docs/resultAnalyze.zh-CN.md
    - name: Deploy to github pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs
        branch: gh-pages
